import { useEffect, useState } from 'react';
import { FlatList, KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing, typography } from '@/constants';
import type { FeedComment, FeedVideo } from '@/types';

export function CommentsSheet({ video, visible, onClose }: { video: FeedVideo | null; visible: boolean; onClose: () => void }) {
  const [comments, setComments] = useState<FeedComment[]>([]); const [draft, setDraft] = useState('');
  useEffect(() => { setComments(video?.comments ?? []); setDraft(''); }, [video]);
  const submit = () => { const message = draft.trim(); if (!message) return; setComments((current) => [{ id: `local-${Date.now()}`, username: 'you', message, timeAgo: 'now', likes: 0 }, ...current]); setDraft(''); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Pressable accessibilityLabel="Close comments" onPress={onClose} style={styles.dismissArea} /><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}><SafeAreaView edges={['bottom']} style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><Text style={styles.title}>{comments.length} comments</Text><Pressable accessibilityLabel="Close comments" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.text} /></Pressable></View>
    <FlatList data={comments} keyExtractor={(item) => item.id} style={styles.list} contentContainerStyle={styles.listContent} keyboardShouldPersistTaps="handled" ListEmptyComponent={<View style={styles.empty}><Ionicons name="chatbubbles-outline" size={32} color={colors.textMuted} /><Text style={styles.emptyTitle}>Start the conversation</Text><Text style={styles.emptyText}>Share encouragement or ask a question.</Text></View>} renderItem={({ item }) => <View style={styles.comment}><View style={styles.commentAvatar}><Text style={styles.avatarText}>{item.username.slice(0, 1).toUpperCase()}</Text></View><View style={styles.commentBody}><Text style={styles.commentUser}>@{item.username} · <Text style={styles.time}>{item.timeAgo}</Text></Text><Text style={styles.message}>{item.message}</Text><Text style={styles.likes}>{item.likes ? `${item.likes} likes` : 'Like'}  ·  Reply</Text></View><Ionicons name="heart-outline" size={17} color={colors.textMuted} /></View>} />
    <View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} onSubmitEditing={submit} placeholder="Add encouragement…" placeholderTextColor={colors.textMuted} selectionColor={colors.accent} style={styles.input} returnKeyType="send" /><Pressable accessibilityLabel="Post comment" disabled={!draft.trim()} onPress={submit} style={[styles.send, !draft.trim() && styles.disabled]}><Ionicons name="arrow-up" size={20} color={colors.background} /></Pressable></View>
  </SafeAreaView></KeyboardAvoidingView></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.55)' }, dismissArea: { flex: 1 }, sheet: { height: '68%', backgroundColor: colors.surface, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg }, handle: { width: 42, height: 4, borderRadius: 2, backgroundColor: colors.border, alignSelf: 'center', marginTop: spacing.sm }, header: { height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }, title: { ...typography.heading, color: colors.text, fontSize: 15 }, close: { position: 'absolute', right: spacing.md, width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, list: { flex: 1 }, listContent: { padding: spacing.md, gap: spacing.lg, flexGrow: 1 }, comment: { flexDirection: 'row', gap: spacing.sm }, commentAvatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#30352D', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.accent, fontWeight: '900' }, commentBody: { flex: 1 }, commentUser: { color: colors.text, fontSize: 12, fontWeight: '800' }, time: { color: colors.textMuted, fontWeight: '500' }, message: { color: colors.text, lineHeight: 20, marginTop: 4 }, likes: { color: colors.textMuted, fontSize: 11, fontWeight: '700', marginTop: spacing.sm }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: colors.text, fontWeight: '800', marginTop: spacing.md }, emptyText: { color: colors.textMuted, fontSize: 12, marginTop: 4 }, composer: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, input: { flex: 1, minHeight: 46, borderRadius: radius.pill, backgroundColor: colors.glass, color: colors.text, paddingHorizontal: spacing.md }, send: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, disabled: { opacity: .35 } });
