import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing, typography } from '@/constants';
import type { FeedVideo } from '@/types';
import { PrimaryButton } from '@/components';

export function CreatorPreviewSheet({ video, visible, following, onFollow, onViewProfile, onReport, onClose }: { video: FeedVideo | null; visible: boolean; following: boolean; onFollow: () => void; onViewProfile: () => void; onReport: () => void; onClose: () => void }) {
  if (!video) return null;
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Pressable style={styles.dismiss} onPress={onClose} /><SafeAreaView edges={['bottom']} style={styles.sheet}><View style={styles.handle} /><Pressable accessibilityLabel="Close creator profile" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.text} /></Pressable><View style={[styles.avatar, { backgroundColor: video.creator.accent }]}><Text style={styles.initials}>{video.creator.initials}</Text></View><View style={styles.nameRow}><Text style={styles.name}>{video.creator.displayName}</Text>{video.creator.verified ? <Ionicons name="checkmark-circle" size={19} color={colors.accent} /> : null}</View><Text style={styles.username}>@{video.creator.username}</Text><Text style={styles.bio}>Fitness creator sharing practical movement, recovery and everyday momentum.</Text><View style={styles.stats}><View><Text style={styles.value}>126K</Text><Text style={styles.label}>FOLLOWERS</Text></View><View><Text style={styles.value}>238</Text><Text style={styles.label}>VIDEOS</Text></View><View><Text style={styles.value}>2.4M</Text><Text style={styles.label}>LIKES</Text></View></View><View style={styles.buttons}><View style={styles.button}><PrimaryButton label={following ? 'Following' : 'Follow'} variant={following ? 'ghost' : 'accent'} onPress={onFollow} /></View><View style={styles.button}><PrimaryButton label="View profile" variant="ghost" onPress={onViewProfile} /></View></View><Pressable onPress={onReport} style={styles.report}><Ionicons name="flag-outline" size={15} color={colors.textMuted} /><Text style={styles.reportText}>Report creator</Text></Pressable></SafeAreaView></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.55)' }, dismiss: { flex: 1 }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, padding: spacing.lg, alignItems: 'center' }, handle: { width: 42, height: 4, borderRadius: 2, backgroundColor: colors.border, marginBottom: spacing.md }, close: { position: 'absolute', right: spacing.md, top: spacing.md, width: 40, height: 40, alignItems: 'center', justifyContent: 'center' }, avatar: { width: 86, height: 86, borderRadius: 43, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: colors.text }, initials: { color: colors.background, fontSize: 25, fontWeight: '900' }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginTop: spacing.md }, name: { ...typography.heading, color: colors.text }, username: { color: colors.accent, fontWeight: '800', marginTop: 3 }, bio: { ...typography.body, color: colors.textMuted, textAlign: 'center', maxWidth: 330, marginTop: spacing.md }, stats: { width: '100%', flexDirection: 'row', justifyContent: 'space-around', marginVertical: spacing.lg }, value: { color: colors.text, fontSize: 18, fontWeight: '900', textAlign: 'center' }, label: { ...typography.label, color: colors.textMuted, fontSize: 8, textAlign: 'center', marginTop: 3 }, buttons: { width: '100%', flexDirection: 'row', gap: spacing.sm }, button: { flex: 1 }, report: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.md, padding: spacing.sm }, reportText: { color: colors.textMuted, fontSize: 12, fontWeight: '700' } });
