import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { AppScreen, PrimaryButton, ReportSheet } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { recipes } from '@/features/demo';
import { forYouVideos } from '@/features/feed/mockFeed';
import type { ReportTarget } from '@/types';

export default function CreatorProfileScreen() {
  const { username } = useLocalSearchParams<{ username: string }>(); const creatorVideos = forYouVideos.filter((video) => video.creator.username === username); const seed = creatorVideos[0] ?? forYouVideos[0]; const [following, setFollowing] = useState(seed.isFollowing); const [report, setReport] = useState<ReportTarget | null>(null); const creatorRecipes = recipes.filter((_, index) => index < 2);
  return <AppScreen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><Pressable accessibilityLabel="Report creator" onPress={() => setReport({ type: 'creator', id: seed.creator.username, label: `@${seed.creator.username}` })}><Ionicons name="ellipsis-horizontal" size={24} color={colors.text} /></Pressable></View>
    <View style={styles.identity}><View style={[styles.avatar, { backgroundColor: seed.creator.accent }]}><Text style={styles.initials}>{seed.creator.initials}</Text></View><View style={styles.nameRow}><Text style={styles.name}>{seed.creator.displayName}</Text>{seed.creator.verified ? <Ionicons name="checkmark-circle" size={19} color={colors.accent} /> : null}</View><Text style={styles.username}>@{seed.creator.username}</Text><Text style={styles.bio}>Practical training, everyday movement and realistic progress. New videos every week.</Text></View>
    <View style={styles.stats}><View><Text style={styles.value}>126K</Text><Text style={styles.label}>FOLLOWERS</Text></View><View><Text style={styles.value}>384</Text><Text style={styles.label}>FOLLOWING</Text></View><View><Text style={styles.value}>2.4M</Text><Text style={styles.label}>LIKES</Text></View></View><PrimaryButton label={following ? 'Following' : 'Follow creator'} variant={following ? 'ghost' : 'accent'} onPress={() => setFollowing((value) => !value)} />
    <Text style={styles.sectionTitle}>VIDEOS</Text><View style={styles.grid}>{(creatorVideos.length ? creatorVideos : forYouVideos.slice(0, 3)).map((video, index) => <Pressable key={video.id} onPress={() => router.push({ pathname: '/(tabs)/feed', params: { videoId: video.id } })} style={[styles.tile, { backgroundColor: index % 2 ? '#26322D' : '#34331F' }]}><Ionicons name="play" size={26} color={colors.accent} /><Text numberOfLines={2} style={styles.tileText}>{video.caption}</Text></Pressable>)}</View>
    <Text style={styles.sectionTitle}>RECIPES</Text>{creatorRecipes.map((recipe) => <Pressable key={recipe.id} onPress={() => Alert.alert('World Cookbook', 'Full recipe pages are added in Phase 6.')} style={styles.recipe}><View style={[styles.recipeAccent, { backgroundColor: recipe.accent }]} /><View style={styles.recipeCopy}><Text style={styles.recipeName}>{recipe.name}</Text><Text style={styles.recipeMeta}>{recipe.protein}g protein · {recipe.prepMinutes} min</Text></View><Ionicons name="chevron-forward" size={20} color={colors.textMuted} /></Pressable>)}
    <Text style={styles.sectionTitle}>INTERESTS</Text><View style={styles.interests}>{seed.categories.map((item) => <View key={item} style={styles.interest}><Text style={styles.interestText}>{item}</Text></View>)}</View><ReportSheet target={report} onClose={() => setReport(null)} />
  </AppScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between' }, identity: { alignItems: 'center', marginTop: spacing.lg }, avatar: { width: 92, height: 92, borderRadius: 46, borderWidth: 3, borderColor: colors.text, alignItems: 'center', justifyContent: 'center' }, initials: { color: colors.background, fontSize: 27, fontWeight: '900' }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginTop: spacing.md }, name: { ...typography.title, fontSize: 24, color: colors.text }, username: { color: colors.accent, fontWeight: '800' }, bio: { ...typography.body, color: colors.textMuted, textAlign: 'center', maxWidth: 330, marginVertical: spacing.md }, stats: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: spacing.lg }, value: { color: colors.text, fontSize: 19, fontWeight: '900', textAlign: 'center' }, label: { ...typography.label, color: colors.textMuted, fontSize: 8, marginTop: 3 }, sectionTitle: { ...typography.label, color: colors.textMuted, marginTop: spacing.xl, marginBottom: spacing.md }, grid: { flexDirection: 'row', gap: spacing.sm }, tile: { flex: 1, aspectRatio: .72, borderRadius: radius.md, padding: spacing.sm, justifyContent: 'flex-end' }, tileText: { color: colors.text, fontSize: 10, fontWeight: '700', marginTop: spacing.sm }, recipe: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, recipeAccent: { width: 44, height: 44, borderRadius: radius.md }, recipeCopy: { flex: 1 }, recipeName: { color: colors.text, fontWeight: '800' }, recipeMeta: { color: colors.textMuted, fontSize: 11, marginTop: 3 }, interests: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, interest: { borderRadius: radius.pill, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: colors.glass }, interestText: { color: colors.text, fontSize: 12, fontWeight: '700' } });
