import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing, typography } from '@/constants';
import { useDemoStore } from '@/features/demo';
import { assistantPrompts, createAssistantReply } from '@/features/assistant/offlineAssistant';

type Message = { id: string; role: 'assistant' | 'user'; text: string };
export default function AssistantScreen() {
  const { foodEntries } = useDemoStore(); const [draft, setDraft] = useState(''); const [messages, setMessages] = useState<Message[]>([{ id: 'welcome', role: 'assistant', text: 'I’m the All Things Fitness demo assistant. I can help with workouts, meal ideas and planning using curated offline guidance. I’m not a doctor and I don’t replace professional medical care.' }]);
  const send = (value = draft) => { const prompt = value.trim(); if (!prompt) return; setMessages((current) => [...current, { id: `u-${Date.now()}`, role: 'user', text: prompt }, { id: `a-${Date.now()}`, role: 'assistant', text: createAssistantReply(prompt, foodEntries) }]); setDraft(''); };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><View style={styles.headerCenter}><View style={styles.online} /><View><Text style={styles.headerTitle}>Fitness Assistant</Text><Text style={styles.headerMeta}>OFFLINE CLIENT DEMO</Text></View></View><Ionicons name="sparkles" size={23} color={colors.accent} /></View><ScrollView style={styles.messages} contentContainerStyle={styles.messageContent} keyboardShouldPersistTaps="handled">{messages.map((message) => <View key={message.id} style={[styles.message, message.role === 'user' ? styles.userMessage : styles.assistantMessage]}>{message.role === 'assistant' ? <Ionicons name="sparkles" size={16} color={colors.accent} /> : null}<Text style={[styles.messageText, message.role === 'user' && styles.userText]}>{message.text}</Text></View>)}<Text style={styles.quickLabel}>QUICK STARTS</Text><View style={styles.quick}>{assistantPrompts.map((prompt) => <Pressable key={prompt} onPress={() => send(prompt)} style={styles.quickChip}><Text style={styles.quickText}>{prompt}</Text></Pressable>)}</View><View style={styles.disclaimer}><Ionicons name="medical-outline" size={19} color={colors.textMuted} /><Text style={styles.disclaimerText}>General education only. Seek qualified care for medical concerns, pain, injury or symptoms.</Text></View></ScrollView><View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="Ask about fitness, food or goals…" placeholderTextColor={colors.textMuted} selectionColor={colors.accent} multiline style={styles.input} /><Pressable accessibilityLabel="Send message" onPress={() => send()} disabled={!draft.trim()} style={[styles.send, !draft.trim() && styles.disabled]}><Ionicons name="arrow-up" size={20} color={colors.background} /></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, flex: { flex: 1 }, header: { minHeight: 66, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border }, headerCenter: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, online: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.success }, headerTitle: { color: colors.text, fontWeight: '900' }, headerMeta: { ...typography.label, color: colors.textMuted, fontSize: 7, marginTop: 2 }, messages: { flex: 1 }, messageContent: { padding: spacing.lg, gap: spacing.md }, message: { maxWidth: '88%', padding: spacing.md, borderRadius: radius.lg, flexDirection: 'row', gap: spacing.sm }, assistantMessage: { alignSelf: 'flex-start', backgroundColor: colors.surfaceElevated, borderBottomLeftRadius: 4 }, userMessage: { alignSelf: 'flex-end', backgroundColor: colors.accent, borderBottomRightRadius: 4 }, messageText: { flex: 1, ...typography.body, color: colors.text }, userText: { color: colors.background, fontWeight: '600' }, quickLabel: { ...typography.label, color: colors.textMuted, fontSize: 8, marginTop: spacing.md }, quick: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, quickChip: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.glass, paddingHorizontal: 12, paddingVertical: 9, borderRadius: radius.pill }, quickText: { color: colors.text, fontSize: 11, fontWeight: '700' }, disclaimer: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: 'rgba(255,255,255,.04)', marginTop: spacing.lg }, disclaimerText: { flex: 1, color: colors.textMuted, fontSize: 10, lineHeight: 15 }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, input: { flex: 1, maxHeight: 100, minHeight: 48, color: colors.text, backgroundColor: colors.glass, borderRadius: radius.lg, paddingHorizontal: spacing.md, paddingTop: 13 }, send: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, disabled: { opacity: .35 } });
