import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { AppScreen, ChoiceChip } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { clubs } from '@/features/demo';
import { useDemoStore } from '@/features/demo';

const filters = ['All', 'Run', 'Class', 'Workshop'];
export default function CommunityScreen() {
  const { events, savedEvents, rsvps } = useDemoStore(); const [tab, setTab] = useState<'clubs' | 'events'>('clubs'); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All'); const query = search.trim().toLowerCase();
  const filteredClubs = useMemo(() => clubs.filter((club) => !query || [club.name, club.type, club.location, ...club.services].some((value) => value.toLowerCase().includes(query))), [query]);
  const filteredEvents = useMemo(() => events.filter((event) => (!query || [event.name, event.type, event.location].some((value) => value.toLowerCase().includes(query))) && (filter === 'All' || event.type === filter)), [events, filter, query]);
  return <AppScreen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><View><Text style={styles.eyebrow}>FIND YOUR PEOPLE</Text><Text style={styles.title}>Community</Text></View><Ionicons name="location" size={23} color={colors.accent} /></View>
    <View style={styles.tabs}><Pressable onPress={() => setTab('clubs')} style={[styles.tab, tab === 'clubs' && styles.activeTab]}><Text style={[styles.tabText, tab === 'clubs' && styles.activeText]}>Clubs</Text></Pressable><Pressable onPress={() => setTab('events')} style={[styles.tab, tab === 'events' && styles.activeTab]}><Text style={[styles.tabText, tab === 'events' && styles.activeText]}>Events</Text></Pressable></View>
    <View style={styles.search}><Ionicons name="search" size={19} color={colors.textMuted} /><TextInput value={search} onChangeText={setSearch} placeholder={`Search ${tab} or location…`} placeholderTextColor={colors.textMuted} style={styles.input} /></View>
    {tab === 'events' ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <ChoiceChip key={item} label={item} selected={filter === item} onPress={() => setFilter(item)} />)}</ScrollView> : <View style={styles.nearby}><Ionicons name="navigate-circle" size={20} color={colors.success} /><Text style={styles.nearbyText}>Showing demo communities near Los Angeles</Text></View>}
    {tab === 'clubs' ? <View style={styles.list}>{filteredClubs.map((club) => <Pressable key={club.id} onPress={() => router.push({ pathname: '/club/[id]', params: { id: club.id } })} style={styles.club}><View style={[styles.clubLogo, { backgroundColor: club.accent }]}><Text style={styles.logoText}>{club.name.split(' ').map((part) => part[0]).slice(0,2).join('')}</Text></View><View style={styles.copy}><Text style={styles.itemTitle}>{club.name}</Text><Text style={styles.meta}>{club.type} · {club.distanceKm} km</Text><Text numberOfLines={2} style={styles.description}>{club.description}</Text><View style={styles.services}>{club.services.slice(0,2).map((service) => <Text key={service} style={styles.service}>{service}</Text>)}</View></View><Ionicons name="chevron-forward" size={20} color={colors.textMuted} /></Pressable>)}</View> : <View style={styles.list}>{filteredEvents.map((event) => { const date = new Date(event.startsAt); return <Pressable key={event.id} onPress={() => router.push({ pathname: '/event/[id]', params: { id: event.id } })} style={styles.event}><View style={[styles.date, { borderColor: event.accent }]}><Text style={[styles.month, { color: event.accent }]}>{date.toLocaleDateString(undefined, { month: 'short' }).toUpperCase()}</Text><Text style={styles.day}>{date.getDate()}</Text></View><View style={styles.copy}><Text style={styles.itemTitle}>{event.name}</Text><Text style={styles.meta}>{date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })} · {event.location}</Text><Text style={styles.description}>{event.attendees + (rsvps.includes(event.id) ? 1 : 0)} going</Text></View><View>{rsvps.includes(event.id) ? <Ionicons name="checkmark-circle" size={20} color={colors.success} /> : savedEvents.includes(event.id) ? <Ionicons name="bookmark" size={19} color={colors.accent} /> : <Ionicons name="chevron-forward" size={20} color={colors.textMuted} />}</View></Pressable>; })}</View>}
  </AppScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { ...typography.label, color: colors.accent, fontSize: 8, textAlign: 'center' }, title: { ...typography.title, color: colors.text, textAlign: 'center' }, tabs: { flexDirection: 'row', backgroundColor: colors.glass, borderRadius: radius.pill, padding: 4, marginTop: spacing.lg }, tab: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: radius.pill }, activeTab: { backgroundColor: colors.accent }, tabText: { color: colors.textMuted, fontWeight: '800' }, activeText: { color: colors.background }, search: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 50, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.border, marginTop: spacing.md }, input: { flex: 1, color: colors.text }, filters: { gap: spacing.sm, paddingVertical: spacing.md }, nearby: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginVertical: spacing.md }, nearbyText: { color: colors.textMuted, fontSize: 11 }, list: { gap: spacing.sm }, club: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surfaceElevated }, clubLogo: { width: 62, height: 62, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, logoText: { color: colors.background, fontWeight: '900', fontSize: 19 }, copy: { flex: 1 }, itemTitle: { color: colors.text, fontWeight: '900', fontSize: 16 }, meta: { color: colors.accent, fontSize: 10, fontWeight: '700', marginTop: 3 }, description: { color: colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 5 }, services: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm }, service: { color: colors.text, fontSize: 9, backgroundColor: colors.glass, paddingHorizontal: 7, paddingVertical: 4, borderRadius: radius.pill }, event: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceElevated }, date: { width: 54, height: 62, borderRadius: radius.md, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, month: { ...typography.label, fontSize: 8 }, day: { color: colors.text, fontSize: 24, fontWeight: '900' } });
