import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { AppScreen } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { useDemoStore } from '@/features/demo';

const icons = { social: 'heart', event: 'calendar', nutrition: 'nutrition', fitness: 'barbell' } as const;
export default function NotificationsScreen() { const { notifications, markNotificationRead, markAllNotificationsRead } = useDemoStore(); const unread = notifications.filter((item) => !item.read).length; return <AppScreen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><Text style={styles.title}>Notifications</Text><Pressable onPress={markAllNotificationsRead}><Text style={styles.readAll}>Read all</Text></Pressable></View><View style={styles.summary}><View><Text style={styles.summaryValue}>{unread}</Text><Text style={styles.summaryText}>UNREAD</Text></View><Pressable onPress={() => router.push('/settings')} style={styles.settings}><Ionicons name="options-outline" size={18} color={colors.text} /><Text style={styles.settingsText}>Preferences</Text></Pressable></View>{notifications.map((notification) => <Pressable key={notification.id} onPress={() => markNotificationRead(notification.id)} style={[styles.item, !notification.read && styles.unread]}><View style={styles.icon}><Ionicons name={icons[notification.type]} size={21} color={colors.accent} /></View><View style={styles.copy}><Text style={styles.itemTitle}>{notification.title}</Text><Text style={styles.body}>{notification.body}</Text><Text style={styles.time}>{notification.time} ago</Text></View>{!notification.read ? <View style={styles.dot} /> : null}</Pressable>)}<View style={styles.demo}><Ionicons name="cloud-offline-outline" size={20} color={colors.textMuted} /><Text style={styles.demoText}>These are local demo notifications. Push delivery requires funded backend and platform credentials.</Text></View></AppScreen>; }
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { ...typography.heading, color: colors.text }, readAll: { color: colors.accent, fontWeight: '800', fontSize: 12 }, summary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: spacing.lg, backgroundColor: '#242419', borderRadius: radius.lg, marginVertical: spacing.lg }, summaryValue: { color: colors.text, fontSize: 28, fontWeight: '900' }, summaryText: { ...typography.label, color: colors.textMuted, fontSize: 8 }, settings: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.glass, padding: 10, borderRadius: radius.pill }, settingsText: { color: colors.text, fontWeight: '700', fontSize: 11 }, item: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, padding: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, unread: { backgroundColor: 'rgba(245,217,10,.04)' }, icon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.glass, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, itemTitle: { color: colors.text, fontWeight: '800' }, body: { color: colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 3 }, time: { color: colors.textMuted, fontSize: 9, marginTop: 5 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accent }, demo: { flexDirection: 'row', gap: spacing.sm, padding: spacing.md, marginTop: spacing.lg }, demoText: { flex: 1, color: colors.textMuted, fontSize: 10, lineHeight: 15 } });
