import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { AppScreen, ChoiceChip, FormField, PrimaryButton } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { useDemoStore } from '@/features/demo';

const meals = ['Breakfast', 'Lunch', 'Dinner', 'Snacks'];
export default function RecipeCreateScreen() {
  const { addRecipe } = useDemoStore(); const [name, setName] = useState(''); const [country, setCountry] = useState(''); const [cuisine, setCuisine] = useState(''); const [meal, setMeal] = useState('Dinner'); const [description, setDescription] = useState(''); const [ingredients, setIngredients] = useState(''); const [instructions, setInstructions] = useState(''); const [prep, setPrep] = useState('25'); const [servings, setServings] = useState('2'); const [calories, setCalories] = useState('500'); const [protein, setProtein] = useState('35'); const [carbs, setCarbs] = useState('50'); const [fat, setFat] = useState('15'); const [photo, setPhoto] = useState('');
  const pick = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('Photo permission needed', 'Allow access to select a recipe photo.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [4, 3], quality: .8 }); if (!result.canceled) setPhoto(result.assets[0].fileName ?? 'Recipe photo selected'); };
  const save = () => { if (!name.trim() || !country.trim() || !ingredients.trim() || !instructions.trim()) { Alert.alert('Complete required fields', 'Recipe name, country, ingredients and instructions are required.'); return; } const id = addRecipe({ name: name.trim(), creator: '@you', country: country.trim(), cuisine: cuisine.trim() || 'Community', meal, dietary: [], calories: Number(calories) || 0, protein: Number(protein) || 0, carbs: Number(carbs) || 0, fat: Number(fat) || 0, prepMinutes: Number(prep) || 0, servings: Number(servings) || 1, description: description.trim() || 'A community-created fitness recipe.', ingredients: ingredients.split('\n').map((value) => value.trim()).filter(Boolean), instructions: instructions.split('\n').map((value) => value.trim()).filter(Boolean), accent: '#C4B5FD' }); router.replace({ pathname: '/recipe/[id]', params: { id } }); };
  return <AppScreen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><Text style={styles.headerTitle}>Create recipe</Text><Text style={styles.demo}>DEMO</Text></View><Text style={styles.title}>Share with the world.</Text><Text style={styles.description}>Build a complete recipe draft. Photo and data remain on this running demo only.</Text><Pressable onPress={() => void pick()} style={styles.photo}><Ionicons name={photo ? 'checkmark-circle' : 'camera-outline'} size={35} color={photo ? colors.success : colors.accent} /><Text style={styles.photoText}>{photo || 'Choose recipe photo'}</Text></Pressable>
    <View style={styles.form}><FormField label="RECIPE NAME *" value={name} onChangeText={setName} placeholder="Your recipe" /><View style={styles.row}><FormField label="COUNTRY *" value={country} onChangeText={setCountry} placeholder="Mexico" containerStyle={styles.field} /><FormField label="CUISINE" value={cuisine} onChangeText={setCuisine} placeholder="Mexican" containerStyle={styles.field} /></View><Text style={styles.label}>MEAL</Text><View style={styles.chips}>{meals.map((item) => <ChoiceChip key={item} label={item} selected={meal === item} onPress={() => setMeal(item)} />)}</View><FormField label="DESCRIPTION" value={description} onChangeText={setDescription} multiline placeholder="What makes it special?" /><FormField label="INGREDIENTS * · ONE PER LINE" value={ingredients} onChangeText={setIngredients} multiline placeholder={'200g chicken\n1 cup rice\nFresh herbs'} /><FormField label="INSTRUCTIONS * · ONE STEP PER LINE" value={instructions} onChangeText={setInstructions} multiline placeholder={'Season and cook protein\nPrepare vegetables\nAssemble and serve'} /><View style={styles.row}><FormField label="PREP MIN" value={prep} onChangeText={setPrep} keyboardType="number-pad" containerStyle={styles.field} /><FormField label="SERVINGS" value={servings} onChangeText={setServings} keyboardType="number-pad" containerStyle={styles.field} /></View><View style={styles.row}><FormField label="CALORIES" value={calories} onChangeText={setCalories} keyboardType="number-pad" containerStyle={styles.field} /><FormField label="PROTEIN G" value={protein} onChangeText={setProtein} keyboardType="number-pad" containerStyle={styles.field} /></View><View style={styles.row}><FormField label="CARBS G" value={carbs} onChangeText={setCarbs} keyboardType="number-pad" containerStyle={styles.field} /><FormField label="FAT G" value={fat} onChangeText={setFat} keyboardType="number-pad" containerStyle={styles.field} /></View><PrimaryButton label="Publish to client demo" onPress={save} /></View></AppScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, headerTitle: { ...typography.heading, color: colors.text }, demo: { ...typography.label, color: colors.accent, fontSize: 8 }, title: { ...typography.title, color: colors.text, marginTop: spacing.xl }, description: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm }, photo: { minHeight: 130, borderRadius: radius.lg, borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(245,217,10,.4)', alignItems: 'center', justifyContent: 'center', marginVertical: spacing.lg, backgroundColor: colors.glass }, photoText: { color: colors.text, fontWeight: '800', marginTop: spacing.sm }, form: { gap: spacing.md }, row: { flexDirection: 'row', gap: spacing.md }, field: { flex: 1 }, label: { ...typography.label, color: colors.textMuted, fontSize: 10 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm } });
