import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { AppScreen, ChoiceChip } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { clubs, useDemoStore } from '@/features/demo';
import { forYouVideos } from '@/features/feed/mockFeed';

type Result = { id: string; type: 'Video' | 'Recipe' | 'Food' | 'Club' | 'Event' | 'Creator'; title: string; subtitle: string; icon: keyof typeof Ionicons.glyphMap; route: () => void };
const filters = ['All', 'Videos', 'Recipes', 'Foods', 'Clubs', 'Events', 'Creators'];
export default function SearchScreen() {
  const { recipes, foodEntries, events } = useDemoStore(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All');
  const results = useMemo<Result[]>(() => {
    const all: Result[] = [
      ...forYouVideos.map((video) => ({ id: video.id, type: 'Video' as const, title: video.caption, subtitle: `@${video.creator.username} · ${video.categories.join(', ')}`, icon: 'play-circle' as const, route: () => router.push({ pathname: '/(tabs)/feed', params: { videoId: video.id } }) })),
      ...recipes.map((recipe) => ({ id: recipe.id, type: 'Recipe' as const, title: recipe.name, subtitle: `${recipe.country} · ${recipe.protein}g protein`, icon: 'restaurant' as const, route: () => router.push({ pathname: '/recipe/[id]', params: { id: recipe.id } }) })),
      ...foodEntries.map((food) => ({ id: food.id, type: 'Food' as const, title: food.name, subtitle: `${food.calories} kcal · ${food.meal}`, icon: 'nutrition' as const, route: () => router.push('/nutrition') })),
      ...clubs.map((club) => ({ id: club.id, type: 'Club' as const, title: club.name, subtitle: `${club.type} · ${club.location}`, icon: 'people' as const, route: () => router.push({ pathname: '/club/[id]', params: { id: club.id } }) })),
      ...events.map((event) => ({ id: event.id, type: 'Event' as const, title: event.name, subtitle: `${event.type} · ${event.location}`, icon: 'calendar' as const, route: () => router.push({ pathname: '/event/[id]', params: { id: event.id } }) })),
      ...forYouVideos.map((video) => ({ id: video.creator.username, type: 'Creator' as const, title: video.creator.displayName, subtitle: `@${video.creator.username}`, icon: 'person-circle' as const, route: () => router.push({ pathname: '/creator/[username]', params: { username: video.creator.username } }) })),
    ];
    const q = query.trim().toLowerCase(); return all.filter((item, index, array) => array.findIndex((candidate) => candidate.id === item.id && candidate.type === item.type) === index && (!q || `${item.title} ${item.subtitle}`.toLowerCase().includes(q)) && (filter === 'All' || `${item.type}s` === filter));
  }, [events, filter, foodEntries, query, recipes]);
  return <AppScreen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><Text style={styles.title}>Search everything</Text><View style={{ width: 24 }} /></View><View style={styles.search}><Ionicons name="search" size={20} color={colors.textMuted} /><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Creators, videos, recipes, foods…" placeholderTextColor={colors.textMuted} style={styles.input} /><Pressable accessibilityLabel="Clear search" onPress={() => setQuery('')}><Ionicons name="close-circle" size={19} color={colors.textMuted} /></Pressable></View><View style={styles.filters}>{filters.map((item) => <ChoiceChip key={item} label={item} selected={filter === item} onPress={() => setFilter(item)} />)}</View><Text style={styles.count}>{results.length} RESULTS</Text>{results.length ? results.map((result) => <Pressable key={`${result.type}-${result.id}`} onPress={result.route} style={styles.result}><View style={styles.icon}><Ionicons name={result.icon} size={22} color={colors.accent} /></View><View style={styles.copy}><Text numberOfLines={1} style={styles.resultTitle}>{result.title}</Text><Text numberOfLines={1} style={styles.subtitle}>{result.type} · {result.subtitle}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.textMuted} /></Pressable>) : <View style={styles.empty}><Ionicons name="search-outline" size={38} color={colors.textMuted} /><Text style={styles.emptyTitle}>Nothing found</Text><Text style={styles.emptyText}>Try broader words or select All.</Text></View>}</AppScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { ...typography.heading, color: colors.text }, search: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 52, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.border, marginTop: spacing.lg }, input: { flex: 1, color: colors.text }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginVertical: spacing.md }, count: { ...typography.label, color: colors.textMuted, fontSize: 8, marginVertical: spacing.sm }, result: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, icon: { width: 42, height: 42, borderRadius: radius.md, backgroundColor: colors.glass, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, resultTitle: { color: colors.text, fontWeight: '800' }, subtitle: { color: colors.textMuted, fontSize: 10, marginTop: 3 }, empty: { alignItems: 'center', paddingTop: spacing.xxl }, emptyTitle: { color: colors.text, fontWeight: '800', marginTop: spacing.md }, emptyText: { color: colors.textMuted, marginTop: 4 } });
