import { useEffect, useRef, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { AppScreen, BrandMark, ChoiceChip, FormField, PrimaryButton } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { useDemoStore } from '@/features/demo';

const categories = ['Workouts', 'Tutorial', 'Nutrition', 'Running', 'Yoga', 'Mobility'];
export default function UploadScreen() {
  const { addUploadedVideo } = useDemoStore(); const [video, setVideo] = useState<ImagePicker.ImagePickerAsset | null>(null); const [thumbnail, setThumbnail] = useState<ImagePicker.ImagePickerAsset | null>(null); const [caption, setCaption] = useState(''); const [category, setCategory] = useState('Workouts'); const [hashtags, setHashtags] = useState('Fitness, Workout'); const [progress, setProgress] = useState(0); const [saving, setSaving] = useState(false); const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  useEffect(() => () => { if (timer.current) clearInterval(timer.current); }, []);
  const pick = async (type: 'video' | 'thumbnail') => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('Media permission needed', 'Allow photo-library access to choose demo media.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: type === 'video' ? ['videos'] : ['images'], allowsEditing: true, quality: .8, videoMaxDuration: 90 }); if (!result.canceled) { if (type === 'video') setVideo(result.assets[0]); else setThumbnail(result.assets[0]); } };
  const save = () => { if (!video) { Alert.alert('Choose a video', 'Select a video before preparing the demo upload.'); return; } if (!caption.trim()) { Alert.alert('Add a caption', 'Tell viewers what the video is about.'); return; } setSaving(true); setProgress(8); timer.current = setInterval(() => setProgress((current) => { const next = Math.min(100, current + 16); if (next === 100) { if (timer.current) clearInterval(timer.current); addUploadedVideo({ uri: video.uri, fileName: video.fileName ?? 'fitness-video.mp4', caption: caption.trim(), category, hashtags: hashtags.split(',').map((value) => value.trim().replace(/^#/, '')).filter(Boolean), status: 'demo-ready' }); setSaving(false); setTimeout(() => { Alert.alert('Demo upload ready', 'The entry was stored in memory. No file was sent to a cloud service.', [{ text: 'View profile', onPress: () => router.replace('/(tabs)/profile') }]); }, 120); } return next; })); };
  return <AppScreen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.text} /></Pressable><BrandMark compact /><Text style={styles.demo}>DEMO</Text></View><Text style={styles.eyebrow}>CREATOR STUDIO</Text><Text style={styles.title}>Share a fitness video.</Text><Text style={styles.description}>Pick media and complete the publishing flow. No cloud upload occurs in client demo mode.</Text>
    <Pressable onPress={() => void pick('video')} style={styles.picker}>{video ? <><Ionicons name="checkmark-circle" size={34} color={colors.success} /><Text style={styles.pickerTitle}>{video.fileName ?? 'Selected video'}</Text><Text style={styles.pickerText}>{video.duration ? `${Math.round(video.duration / 1000)} seconds` : 'Ready for preview'}</Text></> : <><Ionicons name="videocam-outline" size={40} color={colors.accent} /><Text style={styles.pickerTitle}>Choose video</Text><Text style={styles.pickerText}>MP4 or MOV · up to 90 seconds for demo</Text></>}</Pressable>
    <FormField label="CAPTION" value={caption} onChangeText={setCaption} placeholder="What should viewers know?" multiline maxLength={220} />
    <Text style={styles.label}>CATEGORY</Text><View style={styles.chips}>{categories.map((item) => <ChoiceChip key={item} label={item} selected={item === category} onPress={() => setCategory(item)} />)}</View>
    <FormField label="HASHTAGS · COMMA SEPARATED" value={hashtags} onChangeText={setHashtags} placeholder="Fitness, Strength, Tutorial" />
    <Pressable onPress={() => void pick('thumbnail')} style={styles.thumbnail}><Ionicons name={thumbnail ? 'checkmark-circle' : 'image-outline'} size={22} color={thumbnail ? colors.success : colors.accent} /><Text style={styles.thumbnailText}>{thumbnail ? thumbnail.fileName ?? 'Thumbnail selected' : 'Choose optional thumbnail'}</Text></Pressable>
    {saving ? <View style={styles.progressWrap}><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress}%` }]} /></View><Text style={styles.progressText}>Preparing demo · {progress}%</Text></View> : null}
    <View style={styles.actions}><PrimaryButton label="Prepare demo upload" onPress={save} loading={saving} /><Text style={styles.security}>Private server credentials never belong in the mobile app. Phase 4 production uploads will use authenticated storage policies.</Text></View>
  </AppScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xl }, demo: { ...typography.label, color: colors.accent, fontSize: 8 }, eyebrow: { ...typography.label, color: colors.accent }, title: { ...typography.title, color: colors.text, marginTop: spacing.sm }, description: { ...typography.body, color: colors.textMuted, marginTop: spacing.md, marginBottom: spacing.lg }, picker: { minHeight: 168, borderRadius: radius.lg, borderWidth: 1, borderStyle: 'dashed', borderColor: 'rgba(245,217,10,.4)', backgroundColor: '#1C1E18', alignItems: 'center', justifyContent: 'center', padding: spacing.lg, marginBottom: spacing.lg }, pickerTitle: { color: colors.text, fontSize: 17, fontWeight: '800', marginTop: spacing.sm }, pickerText: { color: colors.textMuted, fontSize: 12, marginTop: 4 }, label: { ...typography.label, color: colors.textMuted, fontSize: 10, marginTop: spacing.lg, marginBottom: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, thumbnail: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 50, marginTop: spacing.lg, paddingHorizontal: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.glass }, thumbnailText: { color: colors.text, fontWeight: '700' }, progressWrap: { marginTop: spacing.lg }, progressTrack: { height: 7, borderRadius: 4, backgroundColor: colors.border, overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: colors.accent }, progressText: { color: colors.textMuted, fontSize: 11, marginTop: spacing.sm }, actions: { gap: spacing.md, marginTop: spacing.xl }, security: { color: colors.textMuted, fontSize: 10, textAlign: 'center', lineHeight: 15 } });
