import { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing, typography } from '@/constants';
import { useDemoStore } from '@/features/demo';
import type { ReportTarget } from '@/types';

const reasons = ['Spam or misleading', 'Unsafe activity', 'Harassment', 'Hate or abuse', 'Copyright concern', 'Other'];
export function ReportSheet({ target, onClose }: { target: ReportTarget | null; onClose: () => void }) {
  const { submitReport } = useDemoStore(); const [submitted, setSubmitted] = useState(false);
  useEffect(() => setSubmitted(false), [target]);
  const submit = (reason: string) => { if (!target) return; submitReport(target, reason); setSubmitted(true); };
  return <Modal visible={Boolean(target)} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Pressable style={styles.dismiss} onPress={onClose} /><SafeAreaView edges={['bottom']} style={styles.sheet}><View style={styles.handle} />{submitted ? <View style={styles.confirm}><View style={styles.confirmIcon}><Ionicons name="checkmark" size={27} color={colors.background} /></View><Text style={styles.title}>Report recorded</Text><Text style={styles.description}>This demo stores the report in memory. Phase 4 production wiring will send it to the moderation queue.</Text><Pressable onPress={onClose} style={styles.done}><Text style={styles.doneText}>Done</Text></Pressable></View> : <><Text style={styles.title}>Report {target?.label}</Text><Text style={styles.description}>Choose the reason that best describes the issue.</Text><View style={styles.reasons}>{reasons.map((reason) => <Pressable key={reason} onPress={() => submit(reason)} style={({ pressed }) => [styles.reason, pressed && styles.pressed]}><Text style={styles.reasonText}>{reason}</Text><Ionicons name="chevron-forward" size={18} color={colors.textMuted} /></Pressable>)}</View></>}</SafeAreaView></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.55)' }, dismiss: { flex: 1 }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, padding: spacing.lg }, handle: { width: 42, height: 4, borderRadius: 2, backgroundColor: colors.border, alignSelf: 'center', marginBottom: spacing.lg }, title: { ...typography.heading, color: colors.text, textAlign: 'center' }, description: { ...typography.body, color: colors.textMuted, textAlign: 'center', marginTop: spacing.sm }, reasons: { marginTop: spacing.lg }, reason: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border }, reasonText: { color: colors.text, fontWeight: '700' }, pressed: { opacity: .6 }, confirm: { alignItems: 'center', paddingBottom: spacing.lg }, confirmIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.success, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, done: { marginTop: spacing.lg, backgroundColor: colors.accent, paddingHorizontal: spacing.xl, paddingVertical: 12, borderRadius: radius.pill }, doneText: { color: colors.background, fontWeight: '900' } });
