import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { AppScreen, ChoiceChip } from '@/components';
import { colors, radius, spacing, typography } from '@/constants';
import { useDemoStore } from '@/features/demo';

const filters = ['All', 'Breakfast', 'Lunch', 'Dinner', 'High Protein', 'Vegetarian', 'Vegan'];
export default function CookbookScreen() {
  const { recipes, savedRecipes } = useDemoStore(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All');
  const visible = useMemo(() => recipes.filter((recipe) => { const query = search.trim().toLowerCase(); const matchesSearch = !query || [recipe.name, recipe.country, recipe.cuisine, recipe.creator, ...recipe.ingredients].some((value) => value.toLowerCase().includes(query)); const matchesFilter = filter === 'All' || recipe.meal === filter || recipe.dietary.includes(filter); return matchesSearch && matchesFilter; }), [filter, recipes, search]);
  const hero = visible[0] ?? recipes[0];
  return <AppScreen><View style={styles.header}><View><Text style={styles.eyebrow}>ALL THINGS FITNESS</Text><Text style={styles.title}>World Cookbook</Text></View><Pressable accessibilityLabel="Create recipe" onPress={() => router.push('/recipe-create')} style={styles.create}><Ionicons name="add" size={23} color={colors.background} /></Pressable></View>
    <View style={styles.search}><Ionicons name="search" size={19} color={colors.textMuted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search cuisine, country, ingredients…" placeholderTextColor={colors.textMuted} style={styles.input} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <ChoiceChip key={item} label={item} selected={filter === item} onPress={() => setFilter(item)} />)}</ScrollView>
    {hero && filter === 'All' && !search ? <Pressable onPress={() => router.push({ pathname: '/recipe/[id]', params: { id: hero.id } })} style={[styles.hero, { backgroundColor: hero.accent }]}><View style={styles.heroIcon}><Ionicons name="restaurant" size={34} color={colors.text} /></View><View style={styles.heroBottom}><Text style={styles.heroLabel}>RECIPE OF THE DAY · {hero.country.toUpperCase()}</Text><Text style={styles.heroTitle}>{hero.name}</Text><Text style={styles.heroMeta}>{hero.protein}g protein · {hero.prepMinutes} min · ★ {hero.rating}</Text></View></Pressable> : null}
    <View style={styles.sectionTop}><Text style={styles.sectionTitle}>{search || filter !== 'All' ? `${visible.length} recipes` : 'Explore the world'}</Text><Text style={styles.sort}>POPULAR</Text></View>
    {visible.length ? <View style={styles.grid}>{visible.map((recipe, index) => <Pressable key={recipe.id} onPress={() => router.push({ pathname: '/recipe/[id]', params: { id: recipe.id } })} style={styles.card}><View style={[styles.cardVisual, { backgroundColor: recipe.accent }]}><Ionicons name={index % 2 ? 'leaf' : 'restaurant'} size={30} color={colors.background} />{savedRecipes.includes(recipe.id) ? <View style={styles.saved}><Ionicons name="bookmark" size={14} color={colors.background} /></View> : null}</View><Text numberOfLines={2} style={styles.cardTitle}>{recipe.name}</Text><Text style={styles.cardCountry}>{recipe.country} · {recipe.cuisine}</Text><View style={styles.cardMeta}><Text style={styles.cardStat}>{recipe.calories} kcal</Text><Text style={styles.cardStat}>{recipe.protein}g P</Text></View></Pressable>)}</View> : <View style={styles.empty}><Ionicons name="search-outline" size={34} color={colors.textMuted} /><Text style={styles.emptyTitle}>No recipes match</Text><Text style={styles.emptyText}>Try a different country, ingredient or dietary filter.</Text></View>}
  </AppScreen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { ...typography.label, color: colors.accent, fontSize: 8 }, title: { ...typography.title, color: colors.text, marginTop: 3 }, create: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, search: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 50, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.border, marginTop: spacing.lg }, input: { flex: 1, color: colors.text, fontSize: 14 }, filters: { gap: spacing.sm, paddingVertical: spacing.md }, hero: { height: 240, borderRadius: radius.lg, overflow: 'hidden', padding: spacing.lg, justifyContent: 'space-between' }, heroIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: 'rgba(0,0,0,.22)', alignItems: 'center', justifyContent: 'center' }, heroBottom: { backgroundColor: 'rgba(0,0,0,.62)', padding: spacing.md, borderRadius: radius.md }, heroLabel: { ...typography.label, color: colors.accent, fontSize: 8 }, heroTitle: { color: colors.text, fontSize: 23, fontWeight: '900', marginTop: 4 }, heroMeta: { color: 'rgba(255,255,255,.72)', fontSize: 11, marginTop: 5 }, sectionTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xl, marginBottom: spacing.md }, sectionTitle: { ...typography.heading, color: colors.text }, sort: { ...typography.label, color: colors.textMuted, fontSize: 8 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, card: { width: '47%', marginBottom: spacing.md }, cardVisual: { height: 130, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, saved: { position: 'absolute', right: spacing.sm, top: spacing.sm, width: 28, height: 28, borderRadius: 14, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, cardTitle: { color: colors.text, fontWeight: '900', lineHeight: 18, marginTop: spacing.sm }, cardCountry: { color: colors.textMuted, fontSize: 10, marginTop: 4 }, cardMeta: { flexDirection: 'row', gap: spacing.sm, marginTop: 5 }, cardStat: { color: colors.accentSoft, fontSize: 9, fontWeight: '800' }, empty: { alignItems: 'center', paddingVertical: spacing.xxl }, emptyTitle: { color: colors.text, fontWeight: '800', marginTop: spacing.md }, emptyText: { color: colors.textMuted, textAlign: 'center', marginTop: 4 } });
